---
# This creates the chroot and the launcher.  schroot.yml sets up zoom
# in that chroot.

- name: Install zoom schroot's necessary debian packages
  package:
    name: ["debootstrap", "schroot", "stow"]
    state: latest
  tags:
    - zoom_deps
    
- name: Install schroot configuration file for zoom chroot
  template:
    src: roles/zoom/templates/schroot.d.conf
    dest: /etc/schroot/chroot.d/zoom.conf
    owner: root
    group: root
    mode: '0644' 
  tags:
    - zoom_schroot_setup
 
- name: Create chroot dir {{ zoom_chroot_dir | default('/opt/zoom') }} 
  file:
    path: "{{ zoom_chroot_dir | default('/opt/zoom') }}" 
    state: directory
  tags:
    - zoom_schroot_setup

- name: Install debian into {{ zoom_chroot_dir | default('/opt/zoom') }} chroot (takes a while to complete)
  shell: debootstrap --arch amd64 buster {{ zoom_chroot_dir | default('/opt/zoom') }} http://deb.debian.org/debian
  args:
    creates: "{{ zoom_chroot_dir | default('/opt/zoom') }}/etc"
  when: zoom_chroot_clone is not defined
  tags:
    - zoom_make_chroot
    
- name: Check if "{{ zoom_chroot_dir | default('/opt/zoom') }}/etc" exists
  stat: path="{{ zoom_chroot_dir | default('/opt/zoom') }}/etc"
  register: zoom_st
  tags:
    - zoom_make_chroot
    
- name: Ansible shell register result
  debug: msg="{{ zoom_st.stat.exists }}" 
  when: not zoom_st.stat.exists and zoom_chroot_clone is defined
  tags:
    - zoom_make_chroot

- name: Clone chroot into {{ zoom_chroot_dir | default('/opt/zoom') }} 
  synchronize:
    src: "{{ zoom_chroot_clone }}/"
    dest: "{{ zoom_chroot_dir | default('/opt/zoom') }}"
  delegate_to: "{{ inventory_hostname }}"
  when: not zoom_st.stat.exists and zoom_chroot_clone is defined
  tags:
    - zoom_make_chroot

- name: Add user {{ zoom_schroot_user | default(lookup('env', 'SUDO_USER')) }}
  user:
    name: "{{ zoom_schroot_user | default(lookup('env', 'SUDO_USER')) }}"
    shell: /bin/bash
  tags:
    - zoom_add_user

- name: Make stow dir for zoom
  shell: mkdir -p /usr/local/stow/zoom/bin
  args:
    warn: False
  tags: zoom_install_launcher
  
- name: Stow should ignore local files
  copy:
    src: roles/zoom/files/stow-local-ignore
    dest: /usr/local/stow/zoom/.stow-local-ignore
    owner: root
    group: root
    mode: 0644
  tags: zoom_install_launcher
  
- name: Install zoom launch script
  template:
    src: roles/zoom/templates/zoom
    dest: /usr/local/stow/zoom/bin/zoom
    owner: root
    group: root
    mode: '0755' 
  tags: zoom_install_launcher

- name: Stow zoom
  shell: stow -d /usr/local/stow -R zoom
  tags: zoom_install_launcher
