---
- include: localhost.yml
  tags:
    - zoom_localhost

- include: schroot.yml
  tags:
    - zoom_schroot


# - more steps:
# Download zoom: https://zoom.us/client/latest/zoom_amd64.deb
# enable security sources.list
# apt-update
# dpkg -i zoom.deb
# apt --fix-broken install
# apt install libasound2 libnss3 (nss3 is to get libsmime3.so)
